CREATE SEQUENCE SEQ_USUARIO
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

CREATE TABLE TB_USUARIO (
    USUARIO_ID INTEGER DEFAULT SEQ_USUARIO.NEXTVAL NOT NULL,
    NOME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    SENHA VARCHAR(20) NOT NULL
);