CREATE SEQUENCE SEQ_EVENTO
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

CREATE TABLE TB_EVENTO (
    EVENTO_ID INTEGER DEFAULT SEQ_EVENTO.NEXTVAL NOT NULL,
    NOME VARCHAR2(100) NOT NULL,
    DATA_EVENTO TIMESTAMP NOT NULL,
    LOCAL VARCHAR(255) NOT NULL,
    DESCRICAO CLOB,
    QUANTIDADE_LIMITE INTEGER NOT NULL,
    CONSTRAINT PK_EVENTO PRIMARY KEY (EVENTO_ID)
);